//! The one dependency a Rust project adds to build an agent or otherwise work
//! with LLMs.
//!
//! This crate is a facade: it re-exports the runtime crates of the
//! `grizzly-agent` workspace behind features, so a consumer writes
//! `grizzly_agent::Message` rather than depending on each member crate by
//! name. A bare dependency with no features enabled gets
//! `grizzly-agent-core` alone — conversation types and the error taxonomy,
//! with no provider, skill, or eval machinery pulled in.
//!
//! Every re-export below is curated by name, never a glob, so two members'
//! same-named items can never silently collide or shadow each other.
//! Documentation for each item lives where it is defined, in its member
//! crate; this crate adds none of its own beyond this overview.

// Conversation types. Unconditional: core is a normal (non-optional)
// dependency, so these are present with no features enabled at all.
#[doc(inline)]
pub use grizzly_agent_core::Content;
#[doc(inline)]
pub use grizzly_agent_core::Message;
#[doc(inline)]
pub use grizzly_agent_core::Role;
#[doc(inline)]
pub use grizzly_agent_core::ToolResult;
#[doc(inline)]
pub use grizzly_agent_core::ToolUse;

// The error taxonomy. Unconditional for the same reason.
#[doc(inline)]
pub use grizzly_agent_core::ProviderFailure;
#[doc(inline)]
pub use grizzly_agent_core::RunFailure;
#[doc(inline)]
pub use grizzly_agent_core::ToolFailure;

// The tool model. Unconditional for the same reason: dispatching tools
// through a `ToolSet` needs no provider, skill, or eval feature.
#[doc(inline)]
pub use grizzly_agent_core::DuplicateToolName;
#[doc(inline)]
pub use grizzly_agent_core::NoParams;
#[doc(inline)]
pub use grizzly_agent_core::StopRequest;
#[doc(inline)]
pub use grizzly_agent_core::ToolContext;
#[doc(inline)]
pub use grizzly_agent_core::ToolDefinition;
#[doc(inline)]
pub use grizzly_agent_core::ToolHandler;
#[doc(inline)]
pub use grizzly_agent_core::ToolSet;
#[doc(inline)]
pub use grizzly_agent_core::ToolSpec;
#[doc(inline)]
pub use grizzly_agent_core::TypedToolHandler;

// Model calls and streaming. Unconditional: these are core's, with no
// concrete provider required to use them (a consumer can implement `Provider`
// itself, or use one from `grizzly-agent-providers` once that crate exists).
#[doc(inline)]
pub use grizzly_agent_core::Completion;
#[doc(inline)]
pub use grizzly_agent_core::CompletionAccumulator;
#[doc(inline)]
pub use grizzly_agent_core::CompletionEvent;
#[doc(inline)]
pub use grizzly_agent_core::CompletionRequest;
#[doc(inline)]
pub use grizzly_agent_core::CompletionStream;
#[doc(inline)]
pub use grizzly_agent_core::Model;
#[doc(inline)]
pub use grizzly_agent_core::ModelBuilder;
#[doc(inline)]
pub use grizzly_agent_core::Provider;
#[doc(inline)]
pub use grizzly_agent_core::ResponseFormat;
#[doc(inline)]
pub use grizzly_agent_core::RetryPolicy;
#[doc(inline)]
pub use grizzly_agent_core::StopReason;
#[doc(inline)]
pub use grizzly_agent_core::Usage;

// The turn loop and `Agent`. Unconditional: the loop needs no provider,
// skill, or eval feature — only a `Model` and a `ToolSet`, both already
// unconditional above.
#[doc(inline)]
pub use grizzly_agent_core::Agent;
#[doc(inline)]
pub use grizzly_agent_core::AgentBuilder;
#[doc(inline)]
pub use grizzly_agent_core::DynamicSection;
#[doc(inline)]
pub use grizzly_agent_core::Limits;
#[doc(inline)]
pub use grizzly_agent_core::RoundRecord;
#[doc(inline)]
pub use grizzly_agent_core::RunEnding;
#[doc(inline)]
pub use grizzly_agent_core::RunObserver;
#[doc(inline)]
pub use grizzly_agent_core::RunRecord;
#[doc(inline)]
pub use grizzly_agent_core::RunTrace;
#[doc(inline)]
pub use grizzly_agent_core::SystemSection;
#[doc(inline)]
pub use grizzly_agent_core::ToolCallRecord;

// The OpenAI-compatible provider client.
#[cfg(feature = "openai")]
#[doc(inline)]
pub use grizzly_agent_providers::OpenAiCompatibleProvider;
#[cfg(feature = "openai")]
#[doc(inline)]
pub use grizzly_agent_providers::OpenAiCompatibleProviderBuilder;

// The Anthropic provider client.
#[cfg(feature = "anthropic")]
#[doc(inline)]
pub use grizzly_agent_providers::AnthropicProvider;
#[cfg(feature = "anthropic")]
#[doc(inline)]
pub use grizzly_agent_providers::AnthropicProviderBuilder;

// The scripted provider. Forwarded from core's `test-support` feature.
#[cfg(feature = "test-support")]
#[doc(inline)]
pub use grizzly_agent_core::ScriptedProvider;
#[cfg(feature = "test-support")]
#[doc(inline)]
pub use grizzly_agent_core::ScriptedResponse;

/// Re-exported so code generated by `grizzly-agent-prompts` builds
/// [`ToolSpec::parameters`] against this crate's `serde_json` when a consumer
/// codegens through the facade's default crate path. Not part of the public
/// API; the leading underscore marks it as codegen support that may change
/// without a semver bump.
#[doc(hidden)]
pub use grizzly_agent_core::serde_json;

// ResponseEval and the shared eval core: case metadata, verdicts,
// aggregation, and the report both ResponseEval and AgentEval feed.
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::CaseAggregate;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::CaseMeta;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::CaseReport;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::CaseTimeout;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::CheckResult;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::DEFAULT_MIN_PASS_RATE;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::DEFAULT_REPEATS;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::InvocationDir;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::InvocationDirError;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::REPORT_FILE;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::REPORT_SCHEMA_VERSION;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::RepeatRecord;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::Report;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::ResponseEvalCase;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::ResponseEvalRunner;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::ResponseEvalRunnerBuilder;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::SuiteResult;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::Verdict;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::VerdictCategory;
#[cfg(feature = "eval")]
#[doc(inline)]
pub use grizzly_agent_eval::render_summary;
